### ISSUE TITLE
Entity annotation for сyrillic doesn't work

### ISSUE THREAD

**Issue by nikirg** [botfront/botfront#1001]
I am trying to select an entity, but the settings window does not pop up in cyrillic (russian).  While it works in latin.
Project lang is russian.

**Comment by nprovotorov** [comment]
Strange, but it is "by design" - It was implemented in https://github.com/botfront/botfront/commit/92dfda1aa0f49ca8df76791ad1bcbe7b6fd45f2a

@MatthieuJnon can you please tell what was the reason for this change?

Current issue blocks entire functionality for entity annotation in non-ascii languages (Cyrillic in this case).
