### ISSUE TITLE
botfront-rasa exited with code 132

### ISSUE THREAD

**Issue by ideivitcom** [botfront/botfront#251]
In ubuntu server 18.04
botfront-rasa exited with code 132
Docker version 19.03.3, build a872fc2f86
Node version v12.10.0

1a048c496344        botfront/rasa-for-botfront:v1.3.3-bf.6   "rasa run --enable-a…"   6 minutes ago       Restarting (132) 29 seconds ago                              botfront-rasa

:~/code/botfront/bot1$ botfront

   ┌───────────────────────────┐
   │                           │
   │   Welcome to Botfront!    │
   │   version: 0.16.0-rc.13   │
   │                           │
   └───────────────────────────┘

? What do you want to do? Show logs
TypeError: Cannot destructure property `ci` of 'undefined' or 'null'.
    at Object.dockerComposeFollow [as cmd] (/usr/lib/node_modules/botfront/src/commands/services.js:184:37)
    at general (/usr/lib/node_modules/botfront/src/cli.js:175:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
david@serverlab56:~/code/botfront/bot1$

**Comment by pheel** [comment]
@ideivitcom Exit code 132 is most likely due to the PyPI Tensorflow build requiring a set of instructions unsupported by your CPU. (Your CPU is too old to run Tensorflow.)

The second part of your message is indeed a bug with the CLI--thanks for reporting. You can use `botfront logs` to see your logs.
