### ISSUE TITLE
JS Error on opening webchat botfront ui

### ISSUE THREAD

**Issue by gothax** [botfront/botfront#50]
Hello

I've build 7 containers in Rancher :
bofront-api
mongo-db
rasa-actions-bf
rasa-core-bf
rasa-nlu-bf
rasa-front-bf

When i click on the webchat button on the botfront-ui, the current page become blank.

On the Chrome console, i've got those errors : 
![image](https://user-images.githubusercontent.com/43796533/58944739-b98c7900-8782-11e9-9003-22acdc95d49b.png)

![image](https://user-images.githubusercontent.com/43796533/58944823-da54ce80-8782-11e9-95e1-e05690b21de5.png)

Do you know what could it be ?

I can access to the UI now, Rasa NLU get data when i train it, and API calls to nlu pipeline works.
Rasa-core is running well too.

**Comment by znat** [comment]
Hi @gothax ,
Have you set up environment variables as described in the deployment guide? https://docs.botfront.io/guide/deployment/

**Comment by znat** [comment]
@gothax : looks like you need to define the `ROOT_URL` env var. And make sure your ingress lets websockets in.

**Comment by gothax** [comment]
Hi @znat 
All of my environment variables are defined in every containers.
However, I don't know if my websocket is well available.

It is rasa core which open a websocket endpoint, true ? 

How can i check if my websocket is open ? Where it must be defined ?

**Comment by znat** [comment]
@gothax Your screenshot indicates that `ROOT_URL` is not set. Look at the 1st line: the client try to fetch a dynamic import from `localhost` (which in that case is your computer) while it should fetch it from the server where Botfront is hosted.

Regarding enabling websockets. you can look in your ingress documentation, but it's not the problem here. The problem is that it fails fetching the webchat module from the server. If it was a websocket problem, the webchat would display but not connect to the server

**Comment by amitbend** [comment]
@znat It seems to be another issue, I've also set the ROOT_URL and I saw this issue. I 've changed the core instance address to `<machines_ip>:5005` but now I get `<machines_ip>:5005/socket.io/?EIO=3&transport=polling&t=Mii7ugF et::ERR_CONNECTION_REFUSED`

**Comment by gothax** [comment]
@znat Thanks, i didnt paid attention to this root_url.. damn !

The ip address of my docker is changing every restarts, but i fixed it. Now, it tell me that CORS request are not allowed. (That's better !!)

![image](https://user-images.githubusercontent.com/43796533/59036209-1feec580-886f-11e9-839b-209d869a32d3.png)

**Comment by znat** [comment]
@MatthieuJnon idea ?

**Comment by MatthieuJnon** [comment]
@gothax 
- What have you set root_url to ?
- What ip do you connect to when you go on botfront from your browser ?

because origin should be the url you're currently browsing and the ressource should be fetched from root_utl, so they should be the same, but from your screenshot they don't appear to be the same (172.23.209.187 and 172.23.209.186:3333)

**Comment by gothax** [comment]
Hey @MatthieuJnon @znat 
The problem is the address  of my container is changing every time i update it, or i reboot it...

So root_url is true for the previous conf, but not for the current conf..

I didnt found how to fix public ip address of a container in rancher...

**Comment by gothax** [comment]
@MatthieuJnon @znat It's ok, it works.

For mongodb for example, we can give internal docker address (with rancher stack, so it's the container name).

But for every containers which are calls with the client application (botfront), you have to specify public address
