### ISSUE TITLE
Retrieval response model (ie Response Selector) not working

### ISSUE THREAD

**Issue by predoctech** [botfront/botfront#724]
**Describe the bug**
When importing a story.md embedded with "respond_" syntax, Botfront treated it as a bad line.
ZNAT confirmed it is a bug in Botfront

**To Reproduce**
1. In Stories.md, put in "
* chitchat
   - respond_chitchat
2. Botfront treated the "respond_" syntax as bad lines

**Expected behavior**
Rasa core supports Response Selector

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version 25

**Comment by pheel** [comment]
Hi @predoctech Botfront doesn't support the response selector/retrieval actions at this moment. There is no interface to set training data for responses. Depending on what you are trying to achieve though, [rasa_addons.core.policies.BotfrontMappingPolicy](https://github.com/botfront/rasa-for-botfront/#rasa_addonscorepoliciesbotfrontmappingpolicy) may be a sufficient approximation, because it lets you deterministically map any intent to a response without having to write any custom action.
