### ISSUE TITLE
link to Story

### ISSUE THREAD

**Issue by pcolina** [botfront/botfront#792]
hi everybody!

I am trying to go from 4 branches in my story to another story. It is supossed the "link to" button in the down right corner does it. but when I train it only appear the text from my branch but it does not go to the next story.

I am using debian and firefox to test it

![Screenshot(38)](https://user-images.githubusercontent.com/7817295/97157054-dfe7f580-1777-11eb-92e4-503644912cd2.png)

**Comment by pheel** [comment]
Hi @pcolina,
To debug, check the following:
- What is the first event in `avisos`? (It should be an action or bot utterance)
- What do you find in the tracker instead of that first event, right after the utterance event that maps to "buenas tardes"? What policy predicted it? (You can check this in Incoming > Conversations and toggle the debug mode [🐞]).

**Comment by pcolina** [comment]
The first thing there was in my second  story it was a user payload, and this was the reason it didn't work fine. thanks a lot !

**Comment by pheel** [comment]
Glad you were able to resolve your issue!! 🚀
