### ISSUE TITLE
Model trained in botfront is not working as expected.

### ISSUE THREAD

**Issue by Sharath-Hanumanthaiah** [botfront/botfront#861]
https://stackoverflow.com/questions/65682783/do-botfront-use-the-nlu-data-while-running-model-to-chat

Actually, I trained my dataflow for my chatbot using Botfront. After that for some scenarios used the trained model to run in rasa by using "rasa.agent". But that model is not predicting the intent but it working fine if I run in bot front.

I need to know does the botfront I use the database at runtime to check intent
Can I run that trained model of botfront in rasa.agent.
Do i need to add any extra config to run the model trained botfront in rasa.agent.

**Comment by pheel** [comment]
I'm not sure what you mean by running your model in rasa.agent, but if you mean loading it using `rasa` instead of `rasa-for-botfront`, no. What you can do is export your data using Settings > Import/Export > Export, and select a single language from the dropdown, then train using the exported files.

Feel free to reopen if needed.

**Comment by Sharath-Hanumanthaiah** [comment]
Hi, @pheel  thanks for responding. Is there any way can use **rasa** instead of **rasa-for-botfront**

**Comment by pheel** [comment]
Not at the moment.
